Repository tianocore/edk2-pytool-extensions, pull requests merged in 2019-10, with the labels that each got.

#66 Bug: Fix web dependency hash compare
  edk2toolext/environment/extdeptypes/web_dependency.py
  edk2toolext/tests/test_web_dependency.py
Labels: bug

#57 Doc/creating an invokable
  docs/usability/creating_invocable.md
Labels: documentation, ready

#73 [Bug Fix] Update now no longer fails on a lack of credential provider and properly retries
  docs/usability/using_extdep.md
  edk2toolext/environment/extdeptypes/git_dependency.py
  edk2toolext/environment/extdeptypes/nuget_dependency.py
  edk2toolext/environment/extdeptypes/web_dependency.py
  edk2toolext/environment/external_dependency.py
  edk2toolext/environment/self_describing_environment.py
  edk2toolext/invocables/edk2_update.py
Labels: ready

#74 Submodule recursion support to optimize initialization process
  docs/usability/creating_invocable.md
  docs/usability/using_settings_manager.md
  edk2toolext/base_abstract_invocable.py
  edk2toolext/edk2_invocable.py
  edk2toolext/invocables/edk2_ci_build.py
  edk2toolext/invocables/edk2_ci_setup.py
  edk2toolext/invocables/edk2_platform_build.py
  edk2toolext/invocables/edk2_setup.py
  edk2toolext/invocables/edk2_update.py
Labels: ready

#81 [Bug] Stop suppressing warnings from non root loggers
  edk2toolext/edk2_logging.py
Labels: ready

#83 When an exception occurs when loading settings managers, print out the exception
  edk2toolext/edk2_invocable.py
Labels: ready

#82 Added message in Ci setup to let user know what dependency is being cloned
  edk2toolext/environment/repo_resolver.py
Labels: ready

#88 Bug fix: logic to detect public file dependency in pr eval
  edk2toolext/invocables/edk2_pr_eval.py
Labels: bug

#99 Update build definition to build wheel before testing wheel on releas…
  azure-pipelines/templates/build-publish-whl-steps.yml
  azure-pipelines/templates/build-test-job.yml
Labels: bug
