Repository tianocore/edk2-pytool-extensions, pull requests merged in 2020-05, with the labels that each got.

#113 Update CI Tests for edk2 invokables
  edk2toolext/environment/version_aggregator.py
  edk2toolext/tests/minimal_uefi_tree/Conf/build_rule.template
  edk2toolext/tests/minimal_uefi_tree/Conf/target.template
  edk2toolext/tests/minimal_uefi_tree/Conf/tools_def.template
  edk2toolext/tests/minimal_uefi_tree/Test.dsc
  edk2toolext/tests/minimal_uefi_tree/settings.py
  edk2toolext/tests/test_edk2_ci_build.py
  edk2toolext/tests/test_edk2_ci_setup.py
  edk2toolext/tests/test_edk2_plat_build.py
  edk2toolext/tests/test_edk2_setup.py
  edk2toolext/tests/test_edk2_update.py
  edk2toolext/tests/test_pyopenssl_signer.py
  edk2toolext/tests/test_signtool_signer.py
  edk2toolext/tests/test_version_aggregator.py
  edk2toolext/tests/uefi_tree.py
Labels: Testing improvements, refactor

#193 Clean up invokable SettingsManagers and hierarchy
  edk2toolext/edk2_invocable.py
  edk2toolext/invocables/edk2_ci_build.py
  edk2toolext/invocables/edk2_ci_setup.py
  edk2toolext/invocables/edk2_multipkg_aware_invocable.py
  edk2toolext/invocables/edk2_platform_build.py
  edk2toolext/invocables/edk2_pr_eval.py
  edk2toolext/invocables/edk2_setup.py
  edk2toolext/invocables/edk2_update.py
Labels: bug, enhancement, refactor

#192 Feature/multi thread sde
  edk2toolext/environment/self_describing_environment.py
  edk2toolext/tests/test_edk2_update.py
  edk2toolext/tests/test_self_describing_environment.py
  edk2toolext/tests/uefi_tree.py
Labels: enhancement

#195 Update ci build WalkDirectoryForExtension to use exceptions
  edk2toolext/environment/plugintypes/ci_build_plugin.py
  edk2toolext/tests/test_ci_build_plugin.py
Labels: Testing improvements, bug, documentation, enhancement

#196 Improve structure in Readme
  readme.md
Labels: documentation
