Repository tianocore/edk2-pytool-extensions, pull requests merged in 2020-10, with the labels that each got.

#223 Fix docs for firmware policy
  docs/usability/using_firmware_policy_tool.md
Labels: documentation

#214 Versioninfo tool
  .cspell.json
  .flake8
  azure-pipelines/templates/build-test-job.yml
  docs/usability/using_versioninfo.md
  edk2toolext/tests/test_versioninfo.py
  edk2toolext/tests/testdata/versioninfo_full_exe.data
  edk2toolext/tests/testdata/versioninfo_minimal_exe.data
  edk2toolext/versioninfo/__init__.py
  edk2toolext/versioninfo/versioninfo_helper.py
  edk2toolext/versioninfo/versioninfo_tool.py
  requirements.txt
  setup.py
Labels: enhancement

#220 Refactor override system in SDE
  docs/features/feature_sde.md
  edk2toolext/environment/self_describing_environment.py
  edk2toolext/tests/test_self_describing_environment.py
Labels: bug, enhancement
