Repository tianocore/edk2-pytool-extensions, pull requests merged in 2020-03, with the labels that each got.

#158 [Docs] added pytool diagram for developers
  docs/developing.md
  docs/pytools.png
Labels: documentation, ready

#164 [Bug] Fix setting up parameters for PrEval on version 0.13.x
  edk2toolext/invocables/edk2_pr_eval.py
Labels: bug, ready

#165 Update to Python 3.8.x for unit tests
  azure-pipelines/templates/basic-setup-steps.yml
Labels: ready

#166 Update node to 12.x series for unit test
  azure-pipelines/templates/spell-test-steps.yml
Labels: ready
