Repository tianocore/edk2-pytool-extensions, pull requests merged in 2022-12, with the labels that each got.

#353 Run Integration Tests on last three python minor versions
  integration_test/Shared_Keywords.robot
  integration_test/azure-pipelines/windows-robot-integration-test.yml
  integration_test/edk2_core_ci.robot
  integration_test/edk2_platform_ci.robot
  integration_test/mu_core_ci.robot
  readme.md
Labels: enhancement

#358 Transition CI from azure pipeline to Github Action
  .github/workflows/ci.yml
  azure-pipelines/ubuntu-test-pr-ci.yml
  azure-pipelines/windows-test-pr-ci.yml
  docs/contributor/developing.md
  readme.md
  requirements.txt
Labels: enhancement

#362 Add a check to verify mkdocs builds
  .github/workflows/ci.yml
  docs/contributor/developing.md
  docs/user/requirements.txt
  readme.md
Labels: documentation, enhancement

#364 Add Documentation Deployment Action
  .github/workflows/doc-release.yml
  readme.md
Labels: enhancement

#356 Set close_fds=False when building
  edk2toolext/environment/uefi_build.py
Labels: bug

#355 Add required python version for pypi
  docs/contributor/python_release.md
  setup.py
Labels: enhancement

#369 Add documentation on build values
  docs/user/integrate/build.md
  docs/user/using/build.md
Labels: documentation

#368 Respect git worktrees in the SDE
  .cspell.json
  edk2toolext/environment/self_describing_environment.py
  edk2toolext/tests/test_self_describing_environment.py
  requirements.txt
  setup.py
Labels: enhancement

#371 Synchronize short commit id support
  docs/user/features/extdep.md
  edk2toolext/environment/extdeptypes/git_dependency.py
  edk2toolext/environment/repo_resolver.py
  edk2toolext/tests/test_git_dependency.py
  edk2toolext/tests/test_repo_resolver.py
Labels: enhancement

#373 Remove markdown logging
  docs/user/features/creating_invocable.md
  docs/user/features/logging.md
  edk2toolext/base_abstract_invocable.py
  edk2toolext/edk2_invocable.py
  edk2toolext/edk2_logging.py
  edk2toolext/invocables/edk2_ci_build.py
  edk2toolext/tests/test_edk2_logging.py
  readme.md
Labels: enhancement

#370 Resolve deprecation warning for pyOpenSSL PKCS#12
  edk2toolext/capsule/pyopenssl_signer.py
  edk2toolext/tests/test_pyopenssl_signer.py
Labels: enhancement
