Repository tianocore/edk2-pytool-extensions, pull requests merged in 2022-11, with the labels that each got.

#321 Move dependabot.yml location
  .github/dependabot.yml
Labels: bug

#343 Pydocstyle Updates
  BasicDevTests.py
  azure-pipelines/templates/build-test-job.yml
  azure-pipelines/templates/pydocstyle-test-steps.yml
  docs/developing.md
  edk2toolext/__init__.py
  edk2toolext/bin/__init__.py
  edk2toolext/environment/__init__.py
  edk2toolext/environment/extdeptypes/__init__.py
  edk2toolext/environment/plugintypes/__init__.py
  edk2toolext/invocables/__init__.py
  edk2toolext/tests/__init__.py
Labels: documentation, enhancement

#339 Plugin Loader Updates [Rebase & FF]
  edk2toolext/environment/plugin_manager.py
Labels: enhancement

#341 Allow build wrappers
  docs/usability/environment_variables.md
  edk2toolext/environment/uefi_build.py
  edk2toolext/tests/test_uefi_build.py
Labels: enhancement
