Repository tianocore/edk2-pytool-extensions, pull requests merged in 2023-05, with the labels that each got.

#513 edk2_logging.py: increase specificity of NuGet API key
  edk2toolext/edk2_logging.py
Labels: enhancement

#391 Enable Nuget.exe on MacOS and FreeBSD
  edk2toolext/environment/extdeptypes/nuget_dependency.py
Labels: enhancement

#526 azure-pipelines: build a wheel update
  azure-pipelines/templates/build-publish-whl-steps.yml
Labels: bug

#527 pyproject.toml: update readme content-type
  pyproject.toml
Labels: bug

#529 documentation: remove requirements.txt
  docs/user/requirements.txt
Labels: documentation

#528 MANFIEST.in: additional excludes
  MANIFEST.in
Labels: enhancement, dependencies

#543 tests.integration: update directory
  .github/dependabot.yml
  docs/contributor/python_release.md
  tests.integration/ReadMe.md
  tests.integration/azure-pipelines/windows-robot-integration-test.yml
Labels: bug

#545 uefi_build: missing env error handling
  edk2toolext/environment/uefi_build.py
  tests.unit/test_uefi_build.py
Labels: bug

#547 edk2_logging: add gcc fatal error regex
  edk2toolext/edk2_logging.py
  tests.unit/test_edk2_logging.py
Labels: enhancement

#548 readme: make documentation url more visible
  readme.md
Labels: documentation

#561 uefi_helper_plugin.py: Log plugin load exception message at error level
  edk2toolext/environment/plugintypes/uefi_helper_plugin.py
Labels: enhancement

#566 edk2_logging: Secrets filtering off by default
  docs/user/features/logging.md
  edk2toolext/edk2_logging.py
  tests.unit/test_edk2_logging.py
Labels: enhancement

#570 external_dependency: unsupported host logging
  edk2toolext/environment/external_dependency.py
  tests.unit/test_edk2_update.py
Labels: enhancement

#567 resolve deprecation warnings
  edk2toolext/environment/uefi_build.py
  edk2toolext/invocables/edk2_pr_eval.py
  tests.unit/test_edk2_setup.py
Labels: enhancement

#476 edk2_pr_eval: Add Policy 5
  edk2toolext/invocables/edk2_pr_eval.py
  tests.integration/edk2_stuart_pr_eval.robot
  tests.integration/mu_stuart_pr_eval.robot
Labels: enhancement

#577 dependabot.yml: Update frequency of checks
  .github/dependabot.yml
Labels: dependencies
