Repository tianocore/edk2-pytool-extensions, pull requests merged in 2023-03, with the labels that each got.

#459 Update Cryptography requirement to at least 39.0.1
  requirements.txt
  setup.py
Labels: bug

#465 Fixed setup --force when submodules don't exist
  edk2toolext/environment/repo_resolver.py
  edk2toolext/invocables/edk2_setup.py
  edk2toolext/tests/test_edk2_setup.py
Labels: bug

#460 Update Ubuntu and git documentation
  docs/user/features/using_linux.md
  docs/user/using/install.md
  readme.md
Labels: documentation

#473 dependabot.yml: Add GitHub actions
  .github/dependabot.yml
Labels: enhancement, dependencies
