Repository tianocore/edk2-pytool-extensions, pull requests merged in 2023-02, with the labels that each got.

#429 nuget_publishing: Add repository metadata support
  edk2toolext/nuget_publishing.py
  edk2toolext/tests/test_nuget_publish.py
Labels: enhancement

#437 Update release pipeline unit testing
  azure-pipelines/templates/pytest-test-steps.yml
Labels: bug

#438 Update pypi required dependencies
  requirements.txt
  setup.py
Labels: documentation, enhancement, ready

#439 edk2toolext/nuget: Download NuGet 6.4.0 (latest release)
  edk2toolext/bin/nuget.py
Labels: dependencies

#432 shell_environment: set_shell_var() exception
  edk2toolext/environment/shell_environment.py
  edk2toolext/tests/test_shell_environment.py
Labels: documentation, enhancement, ready

#441 Non valued build variable bugfix
  edk2toolext/environment/var_dict.py
  edk2toolext/tests/test_var_dict.py
Labels: bug

#417 Add CLI env information to the argument parser --help
  docs/user/integrate/build.md
  docs/user/using/build.md
  edk2toolext/edk2_invocable.py
  edk2toolext/environment/uefi_build.py
  edk2toolext/invocables/edk2_platform_build.py
Labels: enhancement, ready

#407 Remove edk2git
  .vscode/settings.json
  edk2toolext/edk2_git.py
  edk2toolext/environment/extdeptypes/git_dependency.py
  edk2toolext/environment/repo_resolver.py
  edk2toolext/environment/self_describing_environment.py
  edk2toolext/invocables/edk2_setup.py
  edk2toolext/tests/test_edk2_setup.py
  edk2toolext/tests/test_git_dependency.py
  edk2toolext/tests/test_repo_resolver.py
  edk2toolext/tests/test_self_describing_environment.py
  edk2toolext/tests/uefi_tree.py
  requirements.txt
  setup.py
Labels: enhancement, ready
