Repository tianocore/edk2-pytool-extensions, pull requests merged in 2024-02, with the labels that each got.

#741 upgrade markdownlint-cli
  .github/workflows/CIRunner.yml
  azure-pipelines/templates/markdown-lint-steps.yml
  readme.md
Labels: dependencies

#746 edk2_invocable: Bugfix for bad argument handling
  edk2toolext/edk2_invocable.py
  tests.unit/test_edk2_setup.py
Labels: bug

#745 coverage_report: Allow package filtering for --by-platform
  edk2toolext/environment/reporttypes/coverage_report.py
Labels: enhancement

#753 edk2_invocable.py: catch invalid arguments
  edk2toolext/edk2_invocable.py
  tests.unit/test_edk2_setup.py
Labels: enhancement

#755 Add the ability to run only the requested plugins
  docs/user/using/ci.md
  edk2toolext/invocables/edk2_ci_build.py
Labels: enhancement

#761 Fix incorrect usage of strip method while accessing the nuget_cache_path
  edk2toolext/environment/extdeptypes/nuget_dependency.py
Labels: bug
