Repository tianocore/edk2-pytool-extensions, pull requests merged in 2024-07, with the labels that each got.

#838 Fix parameter handling in repo_resolver and update logging configuration.
  edk2toolext/edk2_logging.py
  edk2toolext/environment/repo_resolver.py
Labels: bug

#842 Add reference argument to submodule update --init invocations
  edk2toolext/environment/repo_resolver.py
Labels: enhancement

#754 invocables: Update --help information
  .cspell.json
  edk2toolext/edk2_invocable.py
  edk2toolext/invocables/edk2_multipkg_aware_invocable.py
  edk2toolext/invocables/edk2_platform_build.py
Labels: bug, enhancement

#848 Add Rust Environment module
  docs/user/features/rust_environment.md
  edk2toolext/environment/rust.py
  tests.unit/test_rust_environment.py
Labels: enhancement

#856 Documentation: Fix all broken links
  docs/user/features/environment_variables.md
  docs/user/features/extdep.md
  docs/user/features/plugin_manager.md
  docs/user/index.md
  docs/user/integrate/build.md
  docs/user/integrate/manage.md
  docs/user/integrate/reporting.md
  docs/user/using/build.md
  docs/user/using/ci.md
  docs/user/using/install.md
  docs/user/using/reporting.md
  mkdocs.yml
Labels: bug, documentation
